import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#fbf9f9",
        foreground: "#1b1c1c",
        primary: {
          DEFAULT: "#0d631b",
          foreground: "#ffffff",
          fixed: "#a3f69c",
          "fixed-dim": "#88d982",
          container: "#2e7d32",
          "on-container": "#cbffc2",
        },
        secondary: {
          DEFAULT: "#4c616c",
          foreground: "#ffffff",
          fixed: "#cfe6f2",
          "fixed-dim": "#b4cad6",
          container: "#cfe6f2",
          "on-container": "#526772",
        },
        tertiary: {
          DEFAULT: "#774c00",
          foreground: "#ffffff",
          fixed: "#ffddb5",
          "fixed-dim": "#ffb957",
          container: "#986200",
          "on-container": "#ffeede",
        },
        surface: {
          DEFAULT: "#fbf9f9",
          bright: "#fbf9f9",
          dim: "#dbdad9",
          tint: "#1b6d24",
          variant: "#e3e2e2",
          "on-variant": "#40493d",
          container: {
            DEFAULT: "#efeded",
            lowest: "#ffffff",
            low: "#f5f3f3",
            high: "#e9e8e7",
            highest: "#e3e2e2",
          },
        },
        error: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
          container: "#ffdad6",
          "on-container": "#93000a",
        },
        outline: {
          DEFAULT: "#707a6c",
          variant: "#bfcaba",
        },
        inverse: {
          surface: "#303031",
          "on-surface": "#f2f0f0",
          primary: "#88d982",
        },
        // Legacy/Direct mappings from HTML
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005312",
        "secondary-fixed": "#cfe6f2",
        "secondary-fixed-dim": "#b4cad6",
        "on-secondary-fixed": "#071e27",
        "on-secondary-fixed-variant": "#354a53",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#ffb957",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#40493d",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
